#
# YAML Configuration File - app.local
#     Application Configuration File for Local Context
#
# Author: Sam-Mauris Yong / mauris@hotmail.sg
# License: http://www.opensource.org/licenses/bsd-license New BSD License
#

---
app:
  name: "Packfire Framework for PHP"
  version: "1.0-sofia"
  
routing:
  enabled: true

database:
  default: null

...