#
# YAML Configuration File - IoC
#     Inversion of Control - services definition
#
# Author: Sam-Mauris Yong / mauris@hotmail.sg
# License: http://www.opensource.org/licenses/bsd-license New BSD License
#

---
#serviceName:
#  class: className
#  parameters:
#    - param1
#    - param2

...