#
# YAML Configuration File - IoC
#     Inversion of Control definition
#
# Author: Sam-Mauris Yong / mauris@hotmail.sg
# License: http://www.opensource.org/licenses/bsd-license New BSD License
#

---
# Your data goes here

...