#
# YAML Configuration File - routing
#     Routing for the CLI application goes here
#
# Author      : Sam-Mauris Yong / mauris@hotmail.sg
# Copyright   : Copyright (c) 2010-2012, Sam-Mauris Yong
# License     : http://www.opensource.org/licenses/bsd-license New BSD License
#

---

install:
  actual: "controller.pSetupController:installFramework"
  remap:
    i: install
  params:
    install: '.*'
    
create:
  actual: "controller.pSetupController:createApplication"
  remap:
    c: create
  params:
    create: '.*'

phpunitRun:
  actual: "controller.pSetupController:unitTest"
  remap:
    1: 'test'
    't': 'test'
  params:
    'test': true

packfireVersion:
  actual: "controller.pSetupController:version"
  remap:
    1: 'version'
    'v': 'version'
  params:
    'version': true

home:
  actual: "controller.pSetupController:welcome"

...